### ISSUE TITLE
请问在哪里设置控件的开始时间和结束时间

### ISSUE THREAD

**Issue by JoinKing** [UncleQing/SlidingCalendar#1]
请问在哪里设置控件的开始时间和结束时间

**Comment by UncleQing** [comment]
SlidingCalendarView中public void initDate(DateInfoBean fristBean, DateInfoBean endBean) ，传入两个bean，设置上年月日即可

**Comment by JoinKing** [comment]
设置时间段怎么定位到选择的时间段（初始化的时候）
